[project]
name = "dj-restapi-ptc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "TskhupHaokip", email = "vazehaokip@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.1.2",
    "djangorestframework>=3.18.3",
    "djangorestframework-simplejwt>=5.5.1",
    "keyring>=25.7.0",
    "requests>=2.34.2",
]

[project.scripts]
dj-restapi-ptc = "dj_restapi_ptc:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
